title: "Fundamental of Python"
author: "Manish Datt (manish@bioinfo.guru)"
copyright: "2022 bioinfo.guru"
logo: images/logo_final_horizontal.png
execute:
  execute_notebooks: "off" #"auto"

html:
  extra_navbar: ""

launch_buttons:
  binderhub_url: ""

sphinx:
  config:
    html_theme_options:
      use_download_button: false
      extra_navbar: '
	<style>
        .text1{font-size=18pt;}
        .footer1{
            margin: 2em;
            text-align: center;
        }
        .social_media{
            color: #9c51e0;
            font-size: 1.5em;
            word-spacing: 0.5em;
        }
    </style>
	<script src="https://kit.fontawesome.com/578801937d.js" crossorigin="anonymous"></script>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Geo&family=Lato&display=swap" rel="stylesheet">
	<div class="footer1">
        <span class="text1">Connect with </span>
        <span class="text1" style="color:#9c51e0;font-family:Geo;font-size:14pt">bioinfo.guru</span>
        <br>
        <span class="social_media">
        <a href="https://www.facebook.com/profile.php?id=100078250833738"><i class="fa-brands fa-facebook-square social_media"></i></a>
        <a href="https://www.instagram.com/bioinfo.guru/"><i class="fa-brands fa-instagram-square social_media"></i></a>
        <a href="https://www.linkedin.com/in/bioinfo-guru-68a8b7231/"><i class="fa-brands fa-linkedin social_media"></i></a>
        <a href="https://twitter.com/bioinfo_guru"><i class="fa-brands fa-twitter-square social_media"></i></a>
        </span>
    </div>
    '
      extra_footer: <a href="https://bioinfo.guru">Online course catalogue</a>

url: "bioinfo.guru"
